#!/bin/sh
# I run this manually after checking out or updating subversion.
# It fixes various things up that cannot be handled by revision control.

set -e

#
if [ ! -e vendors/fb-php-sdk ]; then
       git clone http://github.com/facebook/php-sdk.git vendors/fb-php-sdk
fi       

if [ ! -e clone_area/ ]; then
	mkdir clone_area
	git clone https://github.com/felixge/debuggable-scraps.git clone_area/debuggable-scraps
fi       


if [ ! -e shells/fixtures.php ]; then
	rm -rf shells/fixtures.php
	ln -s ../clone_area/debuggable-scraps/cakephp/shells/fixtures/fixtures.php   shells/fixtures.php
fi

if [ ! -e shells/fixturize.php ]; then
	rm -rf shells/fixturize.php
	ln -s ../clone_area/debuggable-scraps/cakephp/shells/fixturize/fixturize.php shells/fixturize.php
fi
